apiVersion: skaffold/v2alpha3
kind: Config

profiles:
  - name: prod
    build:
      local:
        push: true
      artifacts:
        - image: zeth/fiap-health-api-prod
          context: api
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - dest: .
                src: "src/**/*.ts"
        - image: zeth/fiap-health-app-prod
          context: app
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - dest: .
                src: "**/*.ts"
    deploy:
      kubectl:
        manifests: [./k8s/production/*]
