apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: zeth/fiap-health-micro-user-prod
          env:
            - name: RABBITMQ_URL
              value: "amqps://ggwgsquk:UJTYEV9Au0QbnKnFIe_D8mv-qwgIkSHN@jackal.rmq.cloudamqp.com/ggwgsquk"
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "isilo.db.elephantsql.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "dacwjapp"
            - name: DB_PASS
              value: "gXLKwnmBf5QEtPqC4KjNsMnL6E2VFq1Q"
            - name: DB_NAME
              value: "dacwjapp"
            - name: DB_SCHEMA
              value: "user_schema"
            - name: GCP_API_KEY
              value: "rr_teste"
            - name: GCP_IDENTITY_TOOLKIT_URL
              value: "https://identitytoolkit.googleapis.com/v1/"
            - name: GCP_SECURE_TOKEN_URL
              value: "https://securetoken.googleapis.com/v1/"
            - name: GCP_STORAGE_BUCKET_NAME
              value: ""
            - name: GCP_CREDENTIAL_BUCKET
              value: "credentials.json"
            - name: GCP_STORAGE_FOLDER_INTO_BUCKET
              value: "FIAP/HEALTH-APP"
            - name: GCP_MEDIC_TENANT_ID
              value: "Medic-u073f"
            - name: GCP_PATIENT_TENANT_ID
              value: "Patient-ru3x6"

---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
