apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: zeth/fiap-health-api-prod
          env:
            - name: JWT_SECRET
              value: "58fcb249ef09ecffa96611119a0c5d111e3b319623fc8eeb55498068d32eb8f1"
            - name: JWT_EXPIRATION_TIME
              value: "3600"
            - name: JWT_REFRESH_SECRET
              value: "b690a85af4bfb6c21b38fd9c5ae50997c9fa9f3c8f1578e8a620a3d5ada71863"
            - name: JWT_REFRESH_EXPIRATION_TIME
              value: "2"
            - name: SERVER_PORT
              value: "3000"
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "db-postgresql-nyc1-76793-do-user-15278867-0.c.db.ondigitalocean.com"
            - name: DB_PORT
              value: "25060"
            - name: DB_USER
              value: "doadmin"
            - name: DB_PASS
              value: "AVNS_sK2f1Z6obA1GdQbKVCd"
            - name: DB_NAME
              value: "defaultdb"
            - name: DB_SSL
              value: "true"
            - name: DB_CERT
              value: "ca-certificate.pem"
            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USER
              value: "marcio.rodrigues@rr-itsolutions.com.br"
            - name: MAIL_PASS
              value: "wbkg kgue loxd npjm"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "credentialsPlacefy.json"
            - name: GCP_STORAGE_BUCKET
              value: "rr_teste"
            - name: GCP_STORAGE_BUCKET_FOLDER
              value: "placefy"
            - name: URL_RECOVERY_PASS
              value: "https://placefybr.app/recuperacao-senha"
            - name: URL_VALIDATE_EMAIL
              value: "https://placefybr.app/validar-email"

---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
